### ISSUE TITLE
Cliquer sur les notes ne renvoie pas  à leur contenu en bas de document

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-vue#65]
Cliquer sur les notes ne renvoie pas  à leur contenu en bas de document
Le contenu des notes en bas de page ne contient pas d'id et n'est donc pas lié par une ancre aux appels de note

cf chartes/lettres-vue#69

**Comment by vicpsl** [comment]
Il conviendrait de : 

- _a minima_, créer une ancre au niveau de la note (liste de notes) afin qu'un clic sur un appel de note renvoie vers celles-ci,
- et à évaluer : un affichage du contenu de la note au survol de l'appel de note.

**Comment by ethieblin** [comment]
Pouvez-vous donner un exemple de document avec une note ? (si possible public sur la démo)

**Comment by vicpsl** [comment]
Voici un exemple, sur deux points d'accès :

**Sur le serveur en ligne** : https://dev.chartes.psl.eu/lettres/documents/5 : 

![image](https://github.com/chartes/lettres-vue/assets/92852428/2abe3e1b-5e68-4418-a847-d93b0f09ac82)

Cliquer sur la note [note] de la transcription passe l'id de la note à l'URL : 
- https://dev.chartes.psl.eu/lettres/documents/5#8
- rien ne se produit à l'écran (absence d'ancre au niveau du conteneur de la note)


**Sur l'instance de test et la base de test que vous avez déployées** : 
http://localhost:9090/documents/6592
![image](https://github.com/chartes/lettres-vue/assets/92852428/ceb9aa90-7214-42f9-b5c8-e0c7f1feabb0)

Cliquer sur la note [2] du `titre` de la lettre passe l'id de la note à l'URL : 
- http://localhost:9090/documents/6592#5891
- rien ne se produit à l'écran (absence d'ancre au niveau du conteneur de la note)
