### ISSUE TITLE
Les notes apparaissent comme [note] au lieu de leur numéro 

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-vue#69]
Les notes devraient apparaître avec leur numéro de note relatif au document.
Faire attention à mettre à jour ce numéro pour toutes les notes (qui n'existe que côté frontend) quand on supprime des notes.

**Comment by vicpsl** [comment]
Resolved "[note]" have been replaced by database index.
Possible evolution : user driven index, stored in db in this case.
